baseURL = "https://throbbinhood.com/"
languageCode = "en-us"
title = "ThrobbinHood"
theme = "PaperMod"

[pagination]
pagerSize = 25

[taxonomies]
genre = "genres"
trope = "tropes"
series = "series"
character = "characters"

[params]
description = "Erotic short stories, retellings, characters, and romance tropes."
ShowReadingTime = true
ShowShareButtons = false
ShowBreadCrumbs = true
ShowPostNavLinks = true